name: "Test Action UV"
description: "Test UV Python Action using astral-sh/uv."
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  tag:
    description: "Tag to Create or Update"
    default: "test"
  data:
    description: "Example Data Input"
  summary:
    description: "Add Summary to Job"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  sha:
    description: "Tag Hash"

runs:
  using: "docker"
  image: "Dockerfile"
