# Project
[project]
name = "test-action-uv"
version = "0.0.0"
requires-python = ">=3.10"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
  "actions-tools[github]",
]

[dependency-groups]
dev = [
  "PyGitHub>=2.8.1",
  "bandit>=1.9.3",
  "black>=26.1.0",
  "isort>=7.0.0",
  "mypy>=1.19.1",
  "pyyaml>=6.0.3",
  "ruff>=0.14.14",
  "tombi>=0.7.23",
  "toml-run>=0.0.2",
  "ty>=0.0.13",
  "types-PyYAML>=6.0.12.20250915",
  "yamllint>=1.38.0",
]

# Bandit
# https://bandit.readthedocs.io/en/latest/config.html
[tool.bandit]
exclude_dirs = [".venv"]

# Black
# https://black.readthedocs.io/en/stable/usage_and_configuration/
[tool.black]
line-length = 119
extend-exclude = '(\.github)'

# Isort
# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
profile = "black"
src_paths = ["src"]
skip = [".venv", ".github"]

# Mypy
# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
# ignore_missing_imports = true
exclude = [".venv"]

# Ruff
# https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 119
target-version = "py313"
extend-exclude = [".github"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "Q"]

# Scripts
# https://github.com/cssnr/toml-run
[tool.scripts]
build = "uv run hatch build"
format = [
  "uv run black .",
  "uv run isort -c .",
  "uv run ruff format .",
  "uv run tombi format .",
  "which prettier && prettier --write . || echo missing prettier",
]
lint = [
  "run bandit",
  "run mypy",
  "run ruff",
  "run yamllint",
  "which prettier && prettier --check . || echo missing prettier",
  "uv run black --check .",
  "uv run isort -c .",
  "uv run tombi lint",
  "uv run ty check -v .",
  "uv lock --check",
]
bandit = "uv run bandit -c pyproject.toml -r ."
mypy = "uv run mypy ."
ruff = "uv run ruff check ."
yamllint = "uv run yamllint -c .github/yamllint.yaml ."
